name: mediaapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.3.0
  shimmer: ^2.0.0
  flutter_map: ^3.0.0
  latlong2: ^0.8.1

assets:
    - assets/images/
    - assets/icons/

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

